dataset:
  datasets:
  - generalizedClick.*
  eval_datasets:
  - generalizedClick.*
  exclude_datasets: []
  root_dir: !!python/object/apply:pathlib.PosixPath
  - /
  - home
  - sagemaker-user
  - brnbci-nfm
  - experiments
  - NDT3
  - Spike_preprocessing
  preprocess_suffix: processed
  explicit_alias_to_session: false
  bin_size_ms: 20
  max_channels: 192
  max_arrays: 1
  behavior_dim: 2
  serve_tokenized: true
  serve_tokenized_flat: true
  neurons_per_token: 32
  tokenize_covariates: true
  pad_spike_value: true
  semantic_positions: {}
  pad_positions: {}
  count_kinematic_in_token_limit: {}
  max_trial_length: 1500
  max_tokens: 8192
  max_length_ms: 1500
  data_keys:
  - spikes
  - bhvr_vel
  meta_keys:
  - subject
  - session
  - array
  - task
  pad_value: 0
  pad_batches: true
  z_score: {}
  verify_preproc: true
  augmentations: []
  rand_augmentations: []
  eval_ratio: 0.05
  tv_ratio: 0.8
  split_key: unique
  eval_seed: 42
  dataset_seed: 42
  split_conditions: false
  eval_split_continuous: true
  train_val_split_continuous: true
  scale_limit_per_session: 1.0
  scale_limit_per_eval_session: 1.0
  scale_limit: 1.0
  scale_ratio: 1.0
  permute_channels: false
  shuffle_neural_space: false
  shuffle_covariate_space: false
  shuffle_targets: false
  generalized_click:
    arrays:
    - brnbciP2-NSP
    behavior_keys:
    - bhvr_vel
    heldout_neurons: 0
model:
  do_rl_step_hotfix: false
  rl:
    replay_buffer_timesteps: 3000
    replay_buffer_traj_length: 1
    online_update_to_data_ratio: 1
    batch_size: 4
    log_interval: 10
    transition_building: pad
    expectile_tau: 0.9
    discount: 0.99
    value_coeff: 0.5
    adv_beta: 1.0
    clip_score: 0.0
    target_tau: 0.01
    target_update_interval: 1
    n_step_returns: 1
    wandb_user: pitt-bci
    wandb_project: ndt3_rl
  compile: false
  hidden_size: 1024
  arch: flash_ndt
  transformer:
    n_state: 1024
    n_heads: 8
    n_layers: 6
    feedforward_factor: 1.0
    dropout: 0.1
    activation: swiglu
    pre_norm: true
    final_norm: true
    flash_as_base: false
    use_biases: false
    use_mlp_biases: true
    use_attn_biases: true
    fused_dropout_add_ln: false
    qk_normalization: true
    initializer_range: 0.0
    initializer_trunc: 0.0
    initializer_rescale_prenorm_residual: true
    learnable_norm: false
    learnable_position: true
    rotary_position: true
    rotary_position_torch: true
    scale_sin: false
    max_trial_length: 1500
    transform_space: true
    flat_encoder: true
    embed_space: true
    max_spatial_tokens: 0
    factorized_space_time: false
    debug_force_nonlearned_position: false
    debug_override_dropout_io: false
    context_integration: in_context
  encode_decode: true
  decoder_layers: 2
  decoder_context_integration: cross_attn
  spike_context_integration: in_context
  use_full_encode: true
  cm3leon_init: false
  next_step_prediction: true
  assert_batch_uniform: false
  token_maskout: 0.0
  kinematic_token_maskout: 0.0
  fit_to_max_length: 0
  kinematic_token_maskout_schedule: random
  kinematic_token_maskout_start: 1.0
  return_conditioned: true
  max_spatial_position: 48
  half_precision: true
  full_half_precision: false
  lr_init: 0.0004
  lr_schedule: cosine_timm
  lr_ramp_init_factor: 0.1
  lr_ramp_steps: 50
  lr_ramp_ratio: 0.0
  lr_interval: epoch
  lr_decay_steps: 100
  lr_min: 1.0e-06
  optimizer: adamw
  sophia_rho: 0.05
  effective_batch_size: 4096
  lr_schedule_hotfix_epoch: 0
  lr_schedule_hotfix_factor: 0.8
  activation: gelu
  weight_decay: 0.01
  weight_decay_fresh: 0.01
  dropout: 0.1
  pretokenize_dropout: 0.0
  preassembly_dropout: 0.0
  postassembly_muting: 0.0
  task:
    tasks:
    - spike_infill
    - kinematic_linear
    task_weights:
    - 1.0
    - 1.0
    - 0.0
    - 0.0
    task_modality_input: []
    delete_params_on_transfer: []
    blacklist_session_supervision: []
    mask_ratio: 0.25
    context_prompt_time_thresh: 0
    context_prompt_time_thresh_min: 750
    prefix_ratio: 0.9
    no_prefix_val: false
    block_prefix_loss: false
    mask_token_ratio: 0.8
    mask_random_ratio: 0.2
    mask_random_shuffle: false
    spike_loss: cross_entropy
    cross_ent_soften: true
    metrics:
    - kinematic_r2_var
    outputs: []
    freeze_backbone: false
    freeze_embed: false
    freeze_all: false
    linear_head: false
    unique_no_head: false
    covariate_mask_ratio: 1.0
    behavior_lag: 0
    behavior_target: bhvr_vel
    behavior_lag_lookahead: true
    behavior_fit_thresh: 0.0
    behavior_metric_thresh: 0.0001
    clip_r2_min: -100000.0
    covariate_blacklist_dims: []
    encode_constraints: true
    use_constraint_cls: false
    behavior_contrastive: ''
    behavior_tolerance: 0.0
    behavior_tolerance_ceil: 0.0
    constraint_mute: false
    constraint_support_mute: false
    constraint_ablate: false
    constraint_noise: 0.0
    return_mute: false
    reward_mute: false
    decode_separate: true
    decode_time_pool: ''
    decode_strategy: token
    decode_tokenize_dims: true
    decode_normalizer: ''
    decode_quantize_classes: 512
    decode_use_shuffle_backbone: false
    decode_label_smooth: 0.0
    decode_hl_gauss_sigma_bin_ratio: 0.0
    decode_symlog: false
    query_heldout: 0
    detach_decode_context: false
  accelerate_new_params: 1.0
  tune_decay: 0.0
  lograte: true
  init_flags: true
  session_embed_strategy: none
  session_embed_size: 1024
  session_embed_token_count: 1
  subject_embed_strategy: none
  subject_embed_size: 1024
  subject_embed_token_count: 1
  task_embed_strategy: none
  task_embed_size: 1024
  task_embed_token_count: 1
  array_embed_strategy: none
  array_embed_size: 1024
  active_assist_embed_strategy: none
  active_assist_embed_size: 1024
  passive_assist_embed_strategy: none
  passive_assist_embed_size: 1024
  readin_strategy: token
  readin_ema: false
  readin_dim: 1024
  readin_compress: true
  readout_strategy: none
  readout_dim: 1024
  stim_embed_strategy: token
  heldout_neuron_embed_strategy: token
  layer_norm_input: false
  transform_space: true
  spike_embed_style: token
  spike_embed_dim: 0
  neurons_per_token: 32
  max_neuron_count: 21
  max_return: 50
  causal: true
  log_backbone_norm: 0
  log_token_seen_throughput: false
  log_token_proc_throughput: true
  debug_project_space: false
  force_zero_mask: false
  val_iters: 1
  closed_loop_crop_bins: 0
  extra_task_embed_ckpt: ''
  extra_subject_embed_ckpt: ''
  eval:
    temperature: 0.0
    teacher_timesteps: 25
    use_student: false
    maskout_last_n: 0
    student_prob: 1.0
    limit_timesteps: 0
    student_gap: 0
    offset_kin_hotfix: 0
    icl_invert: false
    zero_reward: false
    const_return: 0
train:
  max_epochs: 50
  lr: 5.0e-05
  weight_decay: 1.0e-05
  batch_size: 16
  gradient_clip_val: 1.0
  precision: 16
